[package]
name = "doukutsu-save-editor"
version = "0.1.0"
authors = ["poly000 <1348292515@qq.com>"]
edition = "2021"
rust-version = "1.65"
license = "MIT"

[dependencies]
egui = { version = "0.26.2" }
eframe = { version = "0.26.1", features = [
    "accesskit",     # Make egui comptaible with screen readers. NOTE: adds a lot of dependencies.
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",
] }
cavestory-save-lib = "2.9.1"
rfd = "0.13.0"
tracing-subscriber = "0.3"
tokio = { version = "1.36", features = ["rt-multi-thread", "time"] }
tap = "1.0.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }

[profile.dev]
incremental = true

[profile.release]
lto = "thin"
strip = true

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2


[patch.crates-io]

# If you want to use the bleeding edge version of egui and eframe:
# egui = { git = "https://github.com/emilk/egui", branch = "master" }
# eframe = { git = "https://github.com/emilk/egui", branch = "master" }

# If you fork https://github.com/emilk/egui you can test with:
# egui = { path = "../egui/crates/egui" }
# eframe = { path = "../egui/crates/eframe" }
